version: "3.9"

name: open_ai_fast_api

services:
  chat_completion:
    build:
      context: ./01_chat_completion
      dockerfile: Dockerfile
    ports:
      - "8040:8040" 
    volumes:
      - ./01_chat_completion:/code/

  chat_completion_multi_role:
    build:
      context: ./02_chat_completion_multi_role
      dockerfile: Dockerfile
    ports:
      - "8041:8041" 
    volumes:
      - ./02_chat_completion_multi_role:/code/

  streaming:
    build:
      context: ./03_streaming
      dockerfile: Dockerfile
    ports:
      - "8042:8042" 
    volumes:
      - ./03_streaming:/code/

  function_calling:
    build:
      context: ./04_function_calling
      dockerfile: Dockerfile
    ports:
      - "8043:8043" 
    volumes:
      - ./04_function_calling:/code/

  assistants_code_interpreter:
    build:
      context: ./05_assistants_code_interpreter
      dockerfile: Dockerfile
    ports:
      - "8044:8044" 
    volumes:
      - ./05_assistants_code_interpreter:/code/

  assistants_upload_files:
    build:
      context: ./06_assistants_upload_files
      dockerfile: Dockerfile
    ports:
      - "8045:8045" 
    volumes:
      - ./06_assistants_upload_files:/code/

  assistants_function_calling:
    build:
      context: ./07_assistants_function_calling
      dockerfile: Dockerfile
    ports:
      - "8046:8046" 
    volumes:
      - ./07_assistants_function_calling:/code/